language: go
go:
    - "1.10.x"
install:
    - go get github.com/yamamushi/TheAether
    - go get -v .
    - go get -v github.com/golang/lint/golint
    - go get github.com/gordonklaus/ineffassign
    - go get -u github.com/client9/misspell/cmd/misspell
script:
    - diff <(gofmt -d .) <(echo -n)
    - go vet -x ./...
    - golint -set_exit_status ./...
    - ineffassign ./
    - misspell . -error
    - go test -v -race ./...

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL